# Generated by Django 5.0 on 2023-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewievs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('profession', models.CharField(max_length=255, verbose_name='профессия')),
                ('image', models.ImageField(upload_to='image/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
    ]
