# Generated by Django 5.0 on 2023-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='фото1')),
                ('image2', models.ImageField(upload_to='image2/', verbose_name='фото2')),
            ],
            options={
                'verbose_name': 'фото портфолио',
                'verbose_name_plural': 'фото портфолио',
            },
        ),
    ]
