# Generated by Django 5.0 on 2023-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя'),
        ),
    ]
