# Generated by Django 5.0 on 2023-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
